# .air.toml
# 配置air监控和构建

root = "."
tmp_dir = "tmp"

[build]
cmd = "sh /cozeloop/conf/docker/air/hook.sh"
bin = "main"
full_bin = "/cozeloop-bin/backend/dev/main"
include_ext = ["go", "mod", "sum", "tpl", "tmpl"]
exclude_dir = ["tmp", "vendor", ".git", "script", "frontend", "conf"]
delay = 1000

[log]
level = "debug"

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"